name: GitHub Unit Testing Workflow

on:
  push:
    branches: [ "feature/Assignment02" ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
      postgres:
        image: postgres:16
        env:
          DB_URL: ${{ secrets.DB_URL }}        # Database name from GitHub Secrets
          DB_USERNAME: ${{ secrets.DB_USERNAME }}    # Username from GitHub Secrets
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }} # Password from GitHub Secrets
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U DB_USERNAME"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

#      - name: Build with Gradle Wrapper
#        run: ./gradlew build

      - name: UserRestControllerTest Testing
        env:
          DB_URL: ${{ secrets.DB_URL }}        # Database name from GitHub Secrets
          DB_USERNAME: ${{ secrets.DB_USERNAME }}    # Username from GitHub Secrets
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }} # Password from GitHub Secrets
        run: ./gradlew test --stacktrace
